var CCConfig = (function () {
    function CCConfig() {
        this.COCOS2D_DEBUG = 2; //0 to turn debug off, 1 for basic debug, and 2 for full debug
        this.box2d = false;
        this.chipmunk = false;
        this.showFPS = true;
        this.loadExtension = true;
        this.frameRate = 30;
        this.tag = 'gameCanvas'; //the dom element to run cocos2d on
        //    engineDir = 'http://html5-sh.5u5i.com:8008/lib/2.2.2/cocos2d/';
        //    engineDir = 'http://192.168.189.1/html5/cocos2d/cocos2d-html5/tags/Cocos2d-html5-v2.2.2/cocos2d/';
        this.engineDir = null;
        this.SingleEngineFile = 'jsLib/Cocos2d-html5-v2.2.2.min.js';
        //    SingleEngineFile = null;
        this.renderMode = 1;
        this.appFilesMin = [
            'jsLib/howler.js',
            'jsLib/SimpleAudioEngine.js',
            'jsLib/platformTx.js',
            'jsLib/zip.js',
            'jsLib/inflate.js',
            'jsLib/TweenMax.min.js',
            'bin/uphill.min.js'
        ];
        this.appFilesAll = [
            'jsLib/howler.js',
            'jsLib/SimpleAudioEngine.js',
            'jsLib/platformTx.js',
            'jsLib/zip.js',
            'jsLib/inflate.js',
            'src/timonxue/events/EventDispatcher.js',
            'src/timonxue/events/Event.js',
            'src/timonxue/displayObject/DisplayObject.js',
            'src/timonxue/displayObject/TextureAtlas.js',
            'src/timonxue/displayObject/IInteractiveObject.js',
            'src/timonxue/displayObject/InteractiveObject.js',
            'src/timonxue/displayObject/InteractiveNodeRGBA.js',
            'src/timonxue/displayObject/InteractiveLayer.js',
            'src/timonxue/displayObject/InteractiveSprite.js',
            'src/timonxue/utils/DictionaryEx.js',
            'src/timonxue/displayObject/Bitmap.js',
            'src/timonxue/displayObject/BitmapData.js',
            'src/timonxue/displayObject/DragObject.js',
            'src/timonxue/displayObject/MovieClip.js',
            'src/timonxue/events/MouseTouchEvent.js',
            'src/timonxue/math/Matrix.js',
            'src/timonxue/utils/Dictionary.js',
            'src/timonxue/utils/Utils.js',
            'src/timonxue/utils/Attach.js',
            'src/timonxue/utils/SharedObjectUtil.js',
            'src/timonxue/debug/WSSLog.js',
            'src/timonxue/debug/Trace.js',
            'src/timonxue/debug/Stats.js',
            'src/timonxue/debug/FPSSniffer.js',
            'src/timonxue/utils/Timer.js',
            'src/timonxue/ccTx/FileUtilsCCB.js',
            'src/timonxue/ccTx/FixBug2_2_2.js',
            'src/timonxue/ccTx/UIWidgetTx.js',
            'src/timonxue/ccTx/UILayerTx.js',
            'src/timonxue/ccs/WidgetEx.js',
            'src/timonxue/ccs/ImageViewMovieClip.js',
            'src/timonxue/filter/AbstractFilter.js',
            'src/timonxue/filter/BlurFilter.js',
            'src/timonxue/filter/GlowFilter.js',
            'src/riverrun/ZipProxy.js',
            'src/riverrun/Model.js',
            'src/riverrun/localization/Localization.js',
            'src/riverrun/localization/LocalizationEvent.js',
            'src/riverrun/localization/LocalizationSelector.js',
            'src/riverrun/ResPathManager.js',
            'src/riverrun/SoundManager.js',
            'src/riverrun/MusicSound.js',
            'src/riverrun/Filter.js',
            'src/riverrun/PreLoader.js',
            'src/riverrun/Linker.js',
            'src/uphill/ui/UiLoading.js',
            'src/Root.js',
            'src/Resources.js',
            'src/ZPE/math/mVector.js',
            'src/ZPE/math/TF_Class.js',
            'src/ZPE/zpe/$AbstractObject.js',
            'src/ZPE/zpe/$AbstractParticle.js',
            'src/ZPE/zpe/$AbstractCollection.js',
            'src/ZPE/zpe/$AbstractConstraint.js',
            'src/ZPE/zpe/$AbstractWall.js',
            'src/ZPE/zpe/$Collision.js',
            'src/ZPE/zpe/$CollisionDetector.js',
            'src/ZPE/zpe/$CollisionResolver.js',
            'src/ZPE/zpe/$Interval.js',
            'src/ZPE/zpe/$RimParticle.js',
            'src/ZPE/zpe/AngularConstraint.js',
            'src/ZPE/zpe/BezierUtil.js',
            'src/ZPE/zpe/CircleParticle.js',
            'src/ZPE/zpe/CollisionEngine.js',
            'src/ZPE/zpe/CollisionEvent.js',
            'src/ZPE/zpe/Composite.js',
            'src/ZPE/zpe/CurveWall.js',
            'src/ZPE/zpe/Group.js',
            'src/ZPE/zpe/LineUtil.js',
            'src/ZPE/zpe/LineWall.js',
            'src/ZPE/zpe/MathUtil.js',
            'src/ZPE/zpe/RectangleParticle.js',
            'src/ZPE/zpe/SpringConstraint.js',
            'src/ZPE/zpe/WheelParticle.js',
            'src/ZPE/zpe/$SpringConstraintParticle.js',
            'src/TweenMax/TweenMax.min.js',
            'src/TweenMax/easing/EasePack.min.js',
            'src/TweenMax/ZTweenMax.js',
            'src/azUtile/ImageLoader.js',
            'src/azUtile/XMLLoader.js',
            'src/uphill/utils/Utils.js',
            'src/uphill/ui/particlesEffect/ParticleManager.js',
            'src/uphill/ui/events/UiEvents.js',
            'src/uphill/ui/UiManager.js',
            'src/uphill/ui/effects/AbstractEffect.js',
            'src/uphill/ui/effects/PaperEffect.js',
            'src/uphill/ui/screens/AbstractScreen.js',
            'src/uphill/ui/screens/GameUI.js',
            'src/uphill/ui/screens/MainMenuUI.js',
            'src/uphill/ui/screens/ShopUI.js',
            'src/uphill/ui/screens/ChooseModeUI.js',
            'src/uphill/ui/screens/ModeDayUI.js',
            'src/uphill/ui/screens/ModeNightUI.js',
            'src/uphill/ui/screens/GamewinUI.js',
            'src/uphill/ui/screens/GameloseUI.js',
            'src/uphill/ui/screens/RaceFinishUI.js',
            'src/uphill/ui/screens/HelpUI.js',
            'src/uphill/ui/subScreens/AbstractSubScreen.js',
            'src/uphill/ui/subScreens/TryAgainSubScreen.js',
            'src/uphill/ui/subScreens/PauseSubScreen.js',
            'src/uphill/data/xml/XmlVehicleData.js',
            'src/uphill/data/xml/XmlVehicleSoundData.js',
            'src/uphill/data/xml/XmlDesignData.js',
            'src/uphill/game/GameManager.js',
            'src/uphill/game/mission/LayerManager.js',
            'src/uphill/game/mission/Map.js',
            'src/uphill/game/mission/Module.js',
            'src/uphill/game/mission/RandomMap.js',
            'src/uphill/game/models/CameraShake.js',
            'src/uphill/game/models/GameControl.js',
            'src/uphill/game/models/GameInformation.js',
            'src/uphill/game/models/animations/AbstractAnimation.js',
            'src/uphill/game/models/animations/StartAnimation.js',
            'src/uphill/game/models/animations/StuntAnimation.js',
            'src/uphill/game/models/animations/ItemAnimation.js',
            'src/uphill/game/models/animations/CheckAnimation.js',
            'src/uphill/game/models/animations/DestroyAnimation.js',
            'src/uphill/game/player/Z_Player.js',
            'src/uphill/game/player/Z_AbstractCharacter.js',
            'src/uphill/game/player/Z_Driver.js',
            'src/uphill/game/player/Z_Loser.js',
            'src/uphill/game/relation/AbstractRoadRelation.js',
            'src/uphill/game/relation/HideRoadRelation.js',
            'src/uphill/game/relation/SpecialRoadRelation.js',
            'src/uphill/game/road/ISpecialRoad.js',
            'src/uphill/game/road/AbstractRoad.js',
            'src/uphill/game/road/artScene/NormalArtScene.js',
            'src/uphill/game/road/NormalRoad.js',
            'src/uphill/game/road/JumpBoardRoad.js',
            'src/uphill/game/road/AccelerateRoad.js',
            'src/uphill/game/road/DangerRoad.js',
            'src/uphill/game/road/HideRoad.js',
            'src/uphill/game/road/LimitSpeedRoad.js',
            'src/uphill/game/road/ObstacleRoad.js',
            'src/uphill/game/road/BiologicalRoad.js',
            'src/uphill/game/road/RollerCoasterRoad.js',
            'src/uphill/game/road/ControlRelationRoad.js',
            'src/uphill/game/road/FountainRoad.js',
            'src/uphill/game/road/GuideRoad/GuideLineRoad.js',
            'src/uphill/game/road/GuideRoad/GuideLineBox.js',
            'src/uphill/game/road/PoolRoad.js',
            'src/uphill/game/road/StartPointRoad.js',
            'src/uphill/game/road/HangTimeRoad.js',
            'src/uphill/game/road/AirEffectRoad.js',
            'src/uphill/game/road/Item.js',
            'src/uphill/game/road/DrivingSimulatorRoad.js',
            'src/uphill/game/road/CameraShakeRoad.js',
            'src/uphill/game/road/HideWaterEffectRoad.js',
            'src/uphill/game/road/controlTrigger/ControlTriggerRoad.js',
            'src/uphill/game/road/controlTrigger/ControlTriggerInfo.js',
            'src/uphill/game/itemParticles/JumpBoard.js',
            'src/uphill/game/vehicle/vehicleModel/AbstractVehicleModel.js',
            'src/uphill/game/vehicle/vehicleModel/VehicleModel.js',
            'src/uphill/game/vehicle/vehicleModel/LocomotiveModel.js',
            'src/uphill/game/vehicle/newParticle/WeaknessParticle.js',
            'src/uphill/game/vehicle/newParticle/WeaknessDelayParticle.js',
            'src/uphill/game/vehicle/AbstractVehicle.js',
            'src/uphill/game/vehicle/VehicleLocomotive.js',
            'src/uphill/game/action/AbstractAction.js',
            'src/uphill/game/action/NormalAction.js',
            'src/uphill/game/action/AnimalAction.js',
            'src/uphill/game/events/EventBroadcast.js',
            'src/uphill/game/events/JumpBoardEvent.js',
            'src/uphill/game/events/ObstacleBoxEvent.js',
            'src/uphill/game/events/M_RewardEvent.js',
            'src/uphill/game/events/M_LoseEvent.js',
            'src/uphill/game/events/GameEvent.js',
            'src/uphill/game/events/RoadEvent.js',
            'src/uphill/game/handler/BonusHandler.js',
            'src/uphill/game/handler/PlayerMoveHandler.js',
            'src/uphill/data/StringConstData.js',
            'src/uphill/data/GameSetting.js',
            'src/uphill/data/MissionData.js',
            'src/uphill/data/GameData.js',
            'src/uphill/data/ArtResourceNameConst.js',
            'src/uphill/data/AbstractMapData.js',
            'src/uphill/data/BreakingObjectData.js',
            'src/uphill/data/editData/DrawStyle.js',
            'src/uphill/data/editData/ExPropertyData.js',
            'src/uphill/data/editData/GroupData.js',
            'src/uphill/data/editData/EditModuleData.js',
            'src/uphill/data/editData/PointData.js',
            'src/uphill/data/editData/RailData.js',
            'src/uphill/data/editData/EditedNumber.js',
            'src/uphill/data/map/MapData.js',
            'src/uphill/data/map/module/ModuleData.js',
            'src/uphill/data/moduleDoc/ModuleDocData.js',
            'src/uphill/data/moduleDoc/ModuleDocDataManger.js',
            'src/uphill/data/map/road/AbstractRoadData.js',
            'src/uphill/data/map/road/ItemData.js',
            'src/uphill/data/map/road/NormalRoadData.js',
            'src/uphill/data/map/road/JumpBoardData.js',
            'src/uphill/data/map/road/AccelerateRoadData.js',
            'src/uphill/data/map/road/DangerRoadData.js',
            'src/uphill/data/map/road/HideRoadData.js',
            'src/uphill/data/map/road/ControlTriggerData.js',
            'src/uphill/data/map/road/ControlRelationData.js',
            'src/uphill/data/map/road/DrivingSimulatorRoadData.js',
            'src/uphill/data/map/road/LimitSpeedRoadData.js',
            'src/uphill/data/map/road/ObstacleData.js',
            'src/uphill/data/map/road/BiologicalData.js',
            'src/uphill/data/map/road/RollerCoasterRoadData.js',
            'src/uphill/data/map/road/PoolRoadData.js',
            'src/uphill/data/map/road/FountainRoadData.js',
            'src/uphill/data/map/road/StartPointData.js',
            'src/uphill/data/map/road/HangTimeData.js',
            'src/uphill/data/map/road/AirEffectRoadData.js',
            'src/uphill/data/map/road/CameraShakeData.js',
            'src/uphill/data/map/road/GuideRoad/GuideLineRoadData.js',
            'src/uphill/data/map/road/GuideRoad/GuideLineBoxData.js',
            'src/uphill/data/map/road/artScene/NormalArtSceneData.js',
            'src/uphill/data/map/road/artScene/BackArtSceneData.js',
            'src/uphill/data/map/road/HideWaterEffectRoadData.js',
            'src/uphill/data/map/relation/AbstractRelationData.js',
            'src/uphill/data/map/relation/HideRoadRelationData.js',
            'src/uphill/data/map/relation/SpecialRoadRelationData.js',
            'src/uphill/utils/FocusUtile.js',
            'src/uphill/utils/CheckArtVisible.js',
            'src/uphill/utils/DelayPlayFlySound.js',
            'src/uphill/utils/TweenByFrame.js',
            'src/uphill/userData/UserRecord.js',
            'src/uphill/userData/$AbstractRecordData.js',
            'src/uphill/userData/GameSettingData.js',
            'src/uphill/userData/VehicleListData.js',
            'src/uphill/userData/ClothListData.js',
            'src/uphill/userData/MissionListData.js',
            'src/uphill/designObject/ActionTypeRes.js',
            'src/uphill/designObject/DesignCloth.js',
            'src/uphill/designObject/DesignVehicle.js',
            'src/uphill/designObject/DesignStage.js'
        ];
    }
    return CCConfig;
})();
//---------------------------------------------------------------------------------------------------------------------------------------
var Boot = (function () {
    function Boot() {
        window.addEventListener('DOMContentLoaded', function () {
            var config = new CCConfig();
            //            config["appFiles"] = config.appFilesAll;
            config["appFiles"] = config.appFilesMin;
            //first load engine file if specified
            var script = document.createElement('script');
            /*********Delete this section if you have packed all files into one*******/
            if (config.SingleEngineFile && !config.engineDir) {
                script.src = config.SingleEngineFile;
            }
            else if (config.engineDir && !config.SingleEngineFile) {
                script.src = config.engineDir + 'jsloader.js';
            }
            else {
                alert('You must specify either the single engine file OR the engine directory in "cocos2d.js"');
            }
            /*********Delete this section if you have packed all files into one*******/
            //s.src = 'Packed_Release_File.js'; //IMPORTANT: Un-comment this line if you have packed all files into one
            document.body.appendChild(script);
            document["ccConfig"] = config;
            script.id = 'cocos2d-html5';
            //else if single file specified, load singlefile
        });
    }
    return Boot;
})();
new Boot();
//# sourceMappingURL=Boot.js.map